#!/bin/bash

#gnome-terminal -e 'bash -c "./router A 10000 | tee -w outputAfile.txt" & sleep 1;'

#gnome-terminal -e 'bash -c "./router B 10001 | tee -w outputBfile.txt" & sleep 1;'

#gnome-terminal -e 'bash -c "./router C 10002 | tee -w outputCfile.txt" & sleep 1;'

#gnome-terminal -e 'bash -c "./router D 10003 | tee -w outputDfile.txt" & sleep 1;'

#gnome-terminal -e 'bash -c "./router E 10004 | tee -w outputEfile.txt" & sleep 1;'

#gnome-terminal -e 'bash -c "./router F 10005 | tee -w outputFfile.txt" & sleep 1;'

gnome-terminal -e "./my-router A 10000;" 

gnome-terminal -e "./my-router B 10001;"
 
gnome-terminal -e "./my-router C 10002;" 

gnome-terminal -e "./my-router D 10003;" 

gnome-terminal -e "./my-router E 10004;" 

gnome-terminal -e "./my-router F 10005;" 
